#!/usr/bin/env bash
# Derives the iOS build's version metadata from the same sources the Mac app
# uses, so both apps always report one product version and one build number.
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
MAC_ROOT="$(cd "$ROOT/../AddressAtlasMac" && pwd)"
APP_VERSION_SOURCE="$MAC_ROOT/Sources/AddressAtlasMac/AppState.swift"
OUTPUT="${1:-$ROOT/Version.generated.xcconfig}"

APP_VERSION="$(sed -nE 's/^[[:space:]]*static let currentAppVersion = "([0-9]+\.[0-9]+\.[0-9]+)"$/\1/p' "$APP_VERSION_SOURCE")"
if [[ ! "$APP_VERSION" =~ ^[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
  echo "Could not read exactly one three-integer currentAppVersion from $APP_VERSION_SOURCE" >&2
  exit 1
fi

# Honors ADDRESS_ATLAS_BUILD_NUMBER and refuses shallow clones exactly like the Mac build.
BUILD_VERSION="$("$MAC_ROOT/build-mac-app.sh" --print-build-version)"

SOURCE_COMMIT="$(git -C "$ROOT" rev-parse --verify HEAD 2>/dev/null || true)"
if [[ ! "$SOURCE_COMMIT" =~ ^[0-9a-f]{40,64}$ ]]; then
  echo "The iOS app must be built from a Git commit so its source identity can be recorded." >&2
  exit 65
fi

cat > "$OUTPUT" <<XCCONFIG
// Generated by scripts/write-version-xcconfig.sh (git-ignored). Do not edit or commit.
MARKETING_VERSION = $APP_VERSION
CURRENT_PROJECT_VERSION = $BUILD_VERSION
ADDRESS_ATLAS_SOURCE_COMMIT = $SOURCE_COMMIT
XCCONFIG
printf 'Wrote %s (version %s, build %s)\n' "$OUTPUT" "$APP_VERSION" "$BUILD_VERSION"
